export {
  Sparkles,
  Cloud,
  MapPin,
  Bell,
  Users,
  Calendar,
  BookOpen,
  FileText,
  Navigation,
  Moon,
  Eye,
  Settings,
  ChevronRight,
  Plus,
  Heart,
  Check,
  Camera,
  Trophy,
  Wind,
  Info,
  X,
  ArrowRight,
  AlertTriangle,
  Thermometer,
} from 'lucide-react'

export const iconMap = {
  sparkles: 'Sparkles',
  cloud: 'Cloud',
  'map-pin': 'MapPin',
  bell: 'Bell',
  users: 'Users',
  calendar: 'Calendar',
  book: 'BookOpen',
  logbook: 'FileText',
  navigate: 'Navigation',
  moon: 'Moon',
  eye: 'Eye',
  settings: 'Settings',
  'chevron-right': 'ChevronRight',
  plus: 'Plus',
  heart: 'Heart',
  check: 'Check',
  camera: 'Camera',
  trophy: 'Trophy',
  wind: 'Wind',
  info: 'Info',
  x: 'X',
  'arrow-right': 'ArrowRight',
  alert: 'AlertTriangle',
  thermometer: 'Thermometer',
} as const
